import path from "node:path";
import fs from "fs-extra";

export async function writeJianYingDraftKit({
  projectDir,
  projectName,
  ratio = "16:9",
  duration = 90,
  script,
  source,
  audio,
  subtitles,
  cover,
  title,
} = {}) {
  const jianyingDir = path.join(projectDir, "jianying");
  await fs.ensureDir(jianyingDir);

  const storyboard = {
    projectName: projectName || safeProjectName(title || "make-video-auto"),
    ratio,
    width: dimensionsForRatio(ratio).width,
    height: dimensionsForRatio(ratio).height,
    duration,
    title: title || firstTitleLine(script),
    audio,
    subtitles,
    cover,
    visualAssets: collectVisualAssets(source, cover),
    callouts: extractCallouts(script),
    notes: [
      "Generated by make-video auto for the jianying-editor skill.",
      "Run this script after installing/configuring jianying-editor and setting JY_SKILL_ROOT if needed.",
    ],
  };

  const storyboardFile = path.join(jianyingDir, "storyboard.json");
  await fs.writeJson(storyboardFile, storyboard, { spaces: 2 });

  const scriptFile = path.join(jianyingDir, "build_draft.py");
  await fs.writeFile(scriptFile, buildDraftScript(storyboardFile), "utf8");

  return { storyboard: storyboardFile, script: scriptFile };
}

function collectVisualAssets(source, cover) {
  const assets = [];
  if (cover) assets.push({ file: cover, role: "cover" });
  for (const item of [...(source?.downloads || []), ...(source?.localAssets || [])]) {
    if (item?.ok && item.file) {
      assets.push({
        file: item.file,
        role: item.provider === "local" ? "local" : "stock",
        source: item.pageUrl,
      });
    }
  }
  return uniqueAssets(assets);
}

function extractCallouts(script = "") {
  const matches = String(script).match(/(?:\d+(?:\.\d+)?%?|\d+亿|\d+万亿|Q[1-4]|GLM-[\w.]+|Fable|Focus is all we need)/gi) || [];
  return [...new Set(matches)].slice(0, 8);
}

function firstTitleLine(script = "") {
  return String(script).split(/\r?\n/).map((line) => line.trim()).find(Boolean) || "Make Video";
}

function safeProjectName(value) {
  return String(value || "make-video-auto").replace(/[\\/:*?"<>|]/g, "_").slice(0, 48);
}

function dimensionsForRatio(ratio) {
  if (ratio === "9:16") return { width: 1080, height: 1920 };
  if (ratio === "1:1") return { width: 1080, height: 1080 };
  if (ratio === "4:5") return { width: 1080, height: 1350 };
  return { width: 1920, height: 1080 };
}

function uniqueAssets(assets) {
  const seen = new Set();
  return assets.filter((asset) => {
    const key = path.resolve(asset.file);
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

function buildDraftScript(storyboardFile) {
  return `#!/usr/bin/env python3
import json
import os
import sys

current_dir = os.path.dirname(os.path.abspath(__file__))
env_root = os.getenv("JY_SKILL_ROOT", "").strip()
skill_candidates = [
    env_root,
    os.path.join(current_dir, ".agent", "skills", "jianying-editor"),
    os.path.join(current_dir, ".trae", "skills", "jianying-editor"),
    os.path.join(current_dir, ".claude", "skills", "jianying-editor"),
    os.path.join(current_dir, "skills", "jianying-editor"),
    os.path.abspath(".agent/skills/jianying-editor"),
    os.path.dirname(current_dir),
    "/Users/lizhigang/.codex/skills/jianying-editor",
]

scripts_path = None
attempted = []
for candidate in skill_candidates:
    if not candidate:
        continue
    candidate = os.path.abspath(candidate)
    attempted.append(candidate)
    if os.path.exists(os.path.join(candidate, "scripts", "jy_wrapper.py")):
        scripts_path = os.path.join(candidate, "scripts")
        break

if not scripts_path:
    raise ImportError("Could not find jianying-editor/scripts/jy_wrapper.py\\nTried:\\n- " + "\\n- ".join(attempted))

if scripts_path not in sys.path:
    sys.path.insert(0, scripts_path)

from jy_wrapper import JyProject

STORYBOARD = ${JSON.stringify(storyboardFile)}

def seconds(value):
    return f"{float(value):.3f}s"

def main():
    with open(STORYBOARD, "r", encoding="utf-8") as f:
        data = json.load(f)

    project = JyProject(
        data["projectName"],
        width=int(data["width"]),
        height=int(data["height"]),
        overwrite=True,
    )

    total = max(1.0, float(data.get("duration") or 90))
    visual_assets = [item for item in data.get("visualAssets", []) if os.path.exists(item.get("file", ""))]
    per_asset = max(2.0, total / max(1, len(visual_assets)))

    for index, item in enumerate(visual_assets):
        seg = project.add_media_safe(
            item["file"],
            start_time=seconds(index * per_asset),
            duration=seconds(per_asset),
            track_name="VideoTrack",
        )
        if index > 0:
            project.add_transition_simple("叠化", video_segment=seg, duration="0.6s")

    audio = data.get("audio")
    if audio and os.path.exists(audio):
        project.add_audio_safe(audio, start_time="0s", track_name="Narration")

    subtitles = data.get("subtitles")
    if subtitles and os.path.exists(subtitles):
        project.script.import_srt(subtitles, "DynamicSubtitles")

    project.add_text_simple(
        data.get("title") or data["projectName"],
        start_time="0s",
        duration="4s",
        track_name="Title",
        anim_in="复古打字机",
    )

    for idx, text in enumerate(data.get("callouts", [])[:6]):
        project.add_text_simple(
            str(text),
            start_time=seconds(8 + idx * 12),
            duration="3s",
            track_name="Callouts",
            anim_in="弹入",
        )

    project.add_text_simple("AI 资本市场 大模型", start_time="4s", duration="4s", track_name="LowerThirds", anim_in="滑入")
    project.add_effect_simple("故障", start_time="0s", duration="2s")
    project.save()

if __name__ == "__main__":
    main()
`;
}
